---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-davicoelho-com
  namespace: default
spec:
  secretName: vaultwarden-davicoelho-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "vaultwarden.davicoelho.com"
  dnsNames:
  - "vaultwarden.davicoelho.com"