version: '3.9'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    container_name: vaultwarden
    environment:
      WEBSOCKET_ENABLED: "true"
      DOMAIN: "https://vaultwarden.davicoelho.com"
    labels:
      - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.davicoelho.com`)
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=lets-encrypt
      - traefik.port=80
    volumes:
      - ./vw-data/:/data
    networks:
      - web

networks:
  web:
    external: true