apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin-token
  namespace: default
spec:
  encryptedData:
    token: AgDBhGXDQfO39c2LVI4Wl5Ts3WI1gy9gkTS7aOtBK6ldU0fTl+2BP9c6vXBXuv35aAIqCr1ILAnpoIPfgKiJMmmPoXbZLYljZlBqsMDTZT5SgVChu84jkA4YA+/pm+nQHo91n33hidQZRlJ/hruf3pRkbR8mDx7WNJ9RZczpLAfa/GN1iPczul1jNWlEpNq/YkGrcxZtmpHqSgA0XXo1ESo2+52hhAKOoHVr+DVcDm4AUJn09zv8bsgdzbjblTiHRP1e7rscw3F8pUXxHRv2Mft5EjCGUeF4ZDrlp6dmTU2racmAfhENGKBLUHnR128vA9BL1oXARAnutFQhIdV40hXxy4VDvYRtpTwhrtiNLjEqbZkXsL8nCSGaMfswkDrR7QW3GP123GpNqCeOgDl0cviVi52ilXWO7sMDP1FRMpliKaony5VaYWLh2UJwNxYbrMzh8Lkr0Guh1EVF1MNCiZSiWMRuW9eYzI0Ce34eDUZa5B/LI5DWY9iWz5PaJ+YFfQtik7jXV+azWCV8ZQKdovO7wJaqT1HnaPdo0iOWItnMd25yDROxvE20cd9lIfJfsAmE0vRw3a80N46qp1x7aoE5KMfHnlaIEkfBkVO9Fibx8kzzmxPjZO4DU6sJF8l+ukXZIRB6z7HP5XUH0+9eJ1pBwJcVtwG2/0BCMNJPRD8paSxuf0AuHCqmTDJWKGSSChIQNZWT4RGzutS3cKTQx9GLysqogJ2P1Ov5bcerZnkSmgf6jUORqHCp/uvugy4tZ4Q1zSSqK252K4gC1REQ8zUlJ1CPGI+zAmxKi4eDgsK5YTcN4mwUSxpbAUsdrQNzmiBK9U6p+rQQoQHsbbAWRbgUHEZPLmnmn7XGvfFhRf+KjR0ytqwLfA==
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin-token
      namespace: default
    type: Opaque

